framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
             stack:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                # default configuration
                retry_strategy:
                  max_retries: 0
                  # milliseconds delay
                  delay: 1000
                  # causes the delay to be higher before each retry
                  # e.g. 1 second delay, 2 seconds, 4 seconds
                  multiplier: 2
                  max_delay: 0
                  # override all of this with a service that
                  # implements Symfony\Component\Messenger\Retry\RetryStrategyInterface
                  # service: null
                options:
                  exchange:
                    name: stack
                  queues:
                    messages_stack: ~

             batch_fibers:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                  exchange:
                    name: batch_fibers
                  queues:
                    messages_batch_fibers: ~

             batch_asyncawait:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                  exchange:
                    name: batch_asyncawait
                  queues:
                    messages_batch_asyncawait: ~

             failed: 'doctrine://default?queue_name=failed'

        routing:
#            App\Message\EmptyMessage: async            # Route your messages to the transports
            App\Message\ProcessTracking: stack
            App\Message\BatchableFiberProcessTracking: batch_fibers
            App\Message\BatchableAsyncAwaitProcessTracking: batch_asyncawait
            # 'App\Message\YourMessage': async
