version: '3.1'
services:
  php:
    build: docker/php
    volumes:
      - ./:/app
    working_dir: /app
    command: php-fpm
  mariadb:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: 'foobar'
      MYSQL_DATABASE: 'foobar'
    ports:
      - "3306:3306"
    volumes:
      - data_mariadb:/var/lib/mysql
  rabbitmq:
    image: library/rabbitmq:3.7-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

volumes:
  data_mariadb: